fast5:
  dir: /disk1/pore_data/MinION_raw_data_20190504
  prefix: DESKTOP_CHF4GRO_20190504_FAK71722_MN21390_sequencing_run_05_04_19_
  names:
    run02: run_02_87174.fast5
  run_splits:
    run02:
    - name: a
      start: 0
      end: 300
    - name: b
      start: 360
      end: 1080
    - name: c
      start: 1140
      end: 1440
    - name: d
      start: 1500
      end: 2220
    - name: e
      start: 2280
      end: 2580
    - name: f
      start: 2640
      end: 3360
segmentation_params:
  out_prefix: /disk1/pore_data/segmented/peptides/20190504
  min_duration_obs: 10
  signal_threshold: 0.700000
  signal_priors:
    prior_open_pore_mean: 220.000000
    prior_open_pore_std: 35.000000
